### ISSUE TITLE
curl_setopt(): Disabling safe uploads is no longer supported

### ISSUE THREAD

**Issue by gentyzhang** [tencentyun/image-php-sdk#5]
PHP Warning:  curl_setopt(): Disabling safe uploads is no longer supported in  vendor/tencentyun/php-sdk/Tencentyun/Http.php on line 43

PHP 7.0.0 (cli) (built: Dec  2 2015 13:06:23) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by gentyzhang** [comment]
//PHP5
curl_setopt(ch, CURLOPT_POSTFIELDS, array(
    'file' => '@'.realpath('image.png'), 
)); 

//PHP7
curl_setopt(ch, CURLOPT_POSTFIELDS, [
    'file' => new CURLFile(realpath('image.png')), 
]);

**Comment by wintrue** [comment]
if (class_exists('\CURLFile')) {
	$fields = array('file' => new \CURLFile($file));
} else {
	$fields = array('file' => '@' . $file);
}
curl_setopt(ch, CURLOPT_POSTFIELDS,$fields);

**Comment by dengdaiderizi521** [comment]
非常棒！我也在使用了PHP7 发现了这个问题

**Comment by simaguo** [comment]
2015年就出现的问题，为啥我2017年还会碰到这个问题，就不能兼容下吗

**Comment by gentyzhang** [comment]
各位码农心平气和讨论问题。多理解下腾讯云这几年拼命保证服务的态度，摸摸大 ^_^
